// Auto-generated by specdrive install.
import { defineConfig } from 'vitest/config'
import quickpickle from 'quickpickle'

export default defineConfig({
  plugins: [quickpickle()],
  test: {
    include: ['specs/_specdrive/**/*.feature'],
    setupFiles: ['specs/setup.ts'],
  },
})
